# Generated by Django 4.1.5 on 2023-01-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calend_app", "0002_remove_calendar_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="type_day",
            field=models.CharField(
                choices=[("Рабочий", "Рабочий"), ("We", "Выходной")],
                default="Рабочий",
                max_length=15,
            ),
        ),
    ]
