# Generated by Django 4.1.5 on 2023-01-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calend_app", "0003_alter_calendar_type_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="type_day",
            field=models.CharField(
                choices=[("Рабочий", "Рабочий"), ("Выходной", "Выходной")],
                default="Рабочий",
                max_length=15,
            ),
        ),
    ]
