# Generated by Django 4.1.5 on 2023-01-08 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calend_app", "0004_alter_calendar_type_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="date",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="type_day",
            field=models.CharField(
                choices=[("Рабочий", "Рабочий"), ("Выходной", "Выходной")],
                default="Рабочий",
                max_length=15,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="day_event",
            name="date",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calend_app.calendar",
                verbose_name="Дата",
            ),
        ),
        migrations.AlterField(
            model_name="day_event",
            name="text",
            field=models.TextField(verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="day_event",
            name="time_create",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="day_event",
            name="time_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
        ),
    ]
